from pathlib import Path
from io import BytesIO
import tempfile

from flask import Flask, render_template_string, request, send_file

from src.markdown_parser import parse_markdown
from src.ppt_builder import build_presentation


app = Flask(__name__)


PAGE = """
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PPT Generator</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f6f7f9;
      --panel: #ffffff;
      --ink: #172033;
      --muted: #69758a;
      --line: #d9dee7;
      --brand: #1f6feb;
      --brand-dark: #164fa8;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      font-family: "Microsoft YaHei", "Segoe UI", sans-serif;
      background: var(--bg);
      color: var(--ink);
    }
    main {
      width: min(1080px, calc(100% - 32px));
      margin: 32px auto;
    }
    .top {
      display: flex;
      align-items: end;
      justify-content: space-between;
      gap: 24px;
      margin-bottom: 20px;
    }
    h1 {
      margin: 0 0 8px;
      font-size: 34px;
      letter-spacing: 0;
    }
    .sub {
      margin: 0;
      color: var(--muted);
      font-size: 15px;
    }
    .panel {
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 22px;
      box-shadow: 0 12px 30px rgba(23, 32, 51, 0.06);
    }
    form {
      display: grid;
      gap: 18px;
    }
    label {
      display: block;
      margin-bottom: 8px;
      color: #2d3748;
      font-weight: 600;
      font-size: 14px;
    }
    textarea, input[type="text"], input[type="file"] {
      width: 100%;
      border: 1px solid var(--line);
      border-radius: 6px;
      background: #fff;
      color: var(--ink);
      font: inherit;
    }
    textarea {
      min-height: 390px;
      padding: 14px;
      resize: vertical;
      line-height: 1.55;
      font-family: Consolas, "Microsoft YaHei", monospace;
    }
    input[type="text"], input[type="file"] {
      min-height: 42px;
      padding: 8px 10px;
    }
    .grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
    }
    .actions {
      display: flex;
      justify-content: flex-end;
    }
    button {
      min-height: 44px;
      padding: 0 22px;
      border: 0;
      border-radius: 6px;
      background: var(--brand);
      color: #fff;
      font: inherit;
      font-weight: 700;
      cursor: pointer;
    }
    button:hover { background: var(--brand-dark); }
    .hint {
      margin-top: 8px;
      color: var(--muted);
      font-size: 13px;
    }
    @media (max-width: 720px) {
      main { width: min(100% - 20px, 1080px); margin: 18px auto; }
      .top { display: block; }
      h1 { font-size: 28px; }
      .grid { grid-template-columns: 1fr; }
      textarea { min-height: 320px; }
    }
  </style>
</head>
<body>
  <main>
    <div class="top">
      <div>
        <h1>PPT Generator</h1>
        <p class="sub">粘贴 Markdown 或上传 .md 文件，生成可编辑的 PowerPoint。</p>
      </div>
    </div>
    <section class="panel">
      <form method="post" action="/generate" enctype="multipart/form-data">
        <div>
          <label for="markdown_text">Markdown 内容</label>
          <textarea id="markdown_text" name="markdown_text">{{ sample }}</textarea>
          <div class="hint">支持标题、列表、图片语法和 Markdown 表格。</div>
        </div>
        <div class="grid">
          <div>
            <label for="markdown_file">上传 Markdown 文件</label>
            <input id="markdown_file" name="markdown_file" type="file" accept=".md,.markdown,.txt">
          </div>
          <div>
            <label for="footer">页脚文字</label>
            <input id="footer" name="footer" type="text" value="我的PPT生成项目">
          </div>
        </div>
        <div class="actions">
          <button type="submit">生成 PPT</button>
        </div>
      </form>
    </section>
  </main>
</body>
</html>
"""


SAMPLE_MARKDOWN = """# PPT 生成项目演示

根据 Markdown 自动生成 PowerPoint。

## 项目目标

- 输入 Markdown 或文本提纲
- 自动拆分为 PPT 页面
- 生成可编辑的 `.pptx` 文件

## 功能进度表

| 模块 | 状态 | 说明 |
| --- | --- | --- |
| 标题页 | 已完成 | 自动生成封面 |
| 内容页 | 已完成 | 支持段落和列表 |
| 表格页 | 已完成 | 支持 Markdown 表格 |
"""


@app.get("/")
def index():
    return render_template_string(PAGE, sample=SAMPLE_MARKDOWN)


@app.post("/generate")
def generate():
    uploaded_file = request.files.get("markdown_file")
    if uploaded_file and uploaded_file.filename:
        markdown_text = uploaded_file.read().decode("utf-8-sig")
        base_dir = Path.cwd()
    else:
        markdown_text = request.form.get("markdown_text", "")
        base_dir = Path.cwd()

    footer_text = request.form.get("footer") or "Generated by PPT Generator"
    deck = parse_markdown(markdown_text)

    with tempfile.TemporaryDirectory() as temp_dir:
        output_path = Path(temp_dir) / "generated.pptx"
        build_presentation(deck, output_path, image_base_dir=base_dir, footer_text=footer_text)
        pptx_data = BytesIO(output_path.read_bytes())
        return send_file(
            pptx_data,
            as_attachment=True,
            download_name="generated.pptx",
            mimetype="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        )


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=False)
