from pathlib import Path
import argparse

from src.markdown_parser import parse_markdown
from src.ppt_builder import build_presentation


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a PPTX file from Markdown.")
    parser.add_argument("input", help="Path to the Markdown input file.")
    parser.add_argument("output", help="Path to the PPTX output file.")
    parser.add_argument("--footer", default="Generated by PPT Generator", help="Footer text displayed on content slides.")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    deck = parse_markdown(input_path.read_text(encoding="utf-8"))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    build_presentation(deck, output_path, image_base_dir=input_path.parent, footer_text=args.footer)

    print(f"Created {output_path}")


if __name__ == "__main__":
    main()
