from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

from .markdown_parser import Deck, ImageAsset
from .theme import DEFAULT_THEME, Theme


SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)


def build_presentation(
    deck: Deck,
    output_path: Path,
    image_base_dir: Path | None = None,
    theme: Theme = DEFAULT_THEME,
    footer_text: str = "Generated by PPT Generator",
) -> None:
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    _add_title_slide(prs, deck.title, deck.subtitle, theme)
    for slide in deck.slides:
        _add_content_slide(
            prs,
            slide.title,
            slide.body,
            slide.bullets,
            slide.images,
            image_base_dir or output_path.parent,
            theme,
            footer_text,
        )

    prs.save(output_path)


def _add_title_slide(prs: Presentation, title: str, subtitle: str, theme: Theme) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_background(slide, theme.cover_background)

    title_box = slide.shapes.add_textbox(Inches(0.9), Inches(2.1), Inches(11.6), Inches(1.0))
    title_frame = title_box.text_frame
    title_frame.clear()
    p = title_frame.paragraphs[0]
    p.text = title
    p.alignment = PP_ALIGN.CENTER
    run = p.runs[0]
    run.font.size = Pt(42)
    run.font.bold = True
    run.font.name = theme.title_font
    run.font.color.rgb = theme.cover_title_color

    subtitle_box = slide.shapes.add_textbox(Inches(2.0), Inches(3.35), Inches(9.3), Inches(0.6))
    subtitle_frame = subtitle_box.text_frame
    subtitle_frame.clear()
    p = subtitle_frame.paragraphs[0]
    p.text = subtitle
    p.alignment = PP_ALIGN.CENTER
    run = p.runs[0]
    run.font.size = Pt(20)
    run.font.name = theme.body_font
    run.font.color.rgb = theme.cover_subtitle_color


def _add_content_slide(
    prs: Presentation,
    title: str,
    body: list[str],
    bullets: list[str],
    images: list[ImageAsset],
    image_base_dir: Path,
    theme: Theme,
    footer_text: str,
) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_background(slide, theme.slide_background)

    accent = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.7), Inches(1.25), Inches(1.1), Inches(0.06))
    accent.fill.solid()
    accent.fill.fore_color.rgb = theme.accent_color
    accent.line.color.rgb = theme.accent_color

    title_box = slide.shapes.add_textbox(Inches(0.7), Inches(0.45), Inches(12), Inches(0.7))
    title_frame = title_box.text_frame
    title_frame.clear()
    p = title_frame.paragraphs[0]
    p.text = title
    run = p.runs[0]
    run.font.size = Pt(30)
    run.font.bold = True
    run.font.name = theme.title_font
    run.font.color.rgb = theme.title_color

    has_images = bool(images)
    content_width = Inches(5.8) if has_images else Inches(11.4)
    content_box = slide.shapes.add_textbox(Inches(0.95), Inches(1.55), content_width, Inches(5.3))
    frame = content_box.text_frame
    frame.word_wrap = True
    frame.clear()

    items = [*body, *bullets]
    if not items:
        items = [" "]

    for idx, item in enumerate(items):
        p = frame.paragraphs[0] if idx == 0 else frame.add_paragraph()
        p.text = item
        p.level = 0
        p.space_after = Pt(8)
        run = p.runs[0]
        run.font.size = Pt(21)
        run.font.name = theme.body_font
        run.font.color.rgb = theme.body_color

    if images:
        _add_images(slide, images, image_base_dir)

    footer = slide.shapes.add_textbox(Inches(0.7), Inches(7.0), Inches(12), Inches(0.3))
    footer_frame = footer.text_frame
    footer_frame.clear()
    p = footer_frame.paragraphs[0]
    p.text = footer_text
    p.alignment = PP_ALIGN.RIGHT
    run = p.runs[0]
    run.font.size = Pt(10)
    run.font.name = theme.body_font
    run.font.color.rgb = theme.footer_color


def _add_background(slide, color: RGBColor) -> None:
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_images(slide, images: list[ImageAsset], base_dir: Path) -> None:
    slots = _image_slots(len(images))
    for image, slot in zip(images, slots):
        image_path = _resolve_image_path(image.path, base_dir)
        picture = slide.shapes.add_picture(str(image_path), slot["left"], slot["top"])
        _fit_picture(picture, slot["width"], slot["height"])
        picture.left = slot["left"] + int((slot["width"] - picture.width) / 2)
        picture.top = slot["top"] + int((slot["height"] - picture.height) / 2)

        if image.alt:
            caption = slide.shapes.add_textbox(
                slot["left"],
                slot["top"] + slot["height"] + Inches(0.08),
                slot["width"],
                Inches(0.25),
            )
            frame = caption.text_frame
            frame.clear()
            p = frame.paragraphs[0]
            p.text = image.alt
            p.alignment = PP_ALIGN.CENTER
            run = p.runs[0]
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor(100, 116, 139)


def _image_slots(count: int) -> list[dict[str, int]]:
    left = Inches(7.0)
    width = Inches(5.4)
    if count == 1:
        return [{"left": left, "top": Inches(1.7), "width": width, "height": Inches(4.6)}]
    return [
        {"left": left, "top": Inches(1.55), "width": width, "height": Inches(2.3)},
        {"left": left, "top": Inches(4.15), "width": width, "height": Inches(2.3)},
    ]


def _resolve_image_path(image_path: str, base_dir: Path) -> Path:
    path = Path(image_path)
    if not path.is_absolute():
        path = base_dir / path
    if not path.exists():
        raise FileNotFoundError(f"Image file not found: {path}")
    return path


def _fit_picture(picture, max_width: int, max_height: int) -> None:
    width_ratio = max_width / picture.width
    height_ratio = max_height / picture.height
    ratio = min(width_ratio, height_ratio)
    picture.width = int(picture.width * ratio)
    picture.height = int(picture.height * ratio)
