from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

from .markdown_parser import Deck


SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)


def build_presentation(deck: Deck, output_path: Path) -> None:
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    _add_title_slide(prs, deck.title, deck.subtitle)
    for slide in deck.slides:
        _add_content_slide(prs, slide.title, slide.body, slide.bullets)

    prs.save(output_path)


def _add_title_slide(prs: Presentation, title: str, subtitle: str) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_background(slide, RGBColor(18, 40, 70))

    title_box = slide.shapes.add_textbox(Inches(0.9), Inches(2.1), Inches(11.6), Inches(1.0))
    title_frame = title_box.text_frame
    title_frame.clear()
    p = title_frame.paragraphs[0]
    p.text = title
    p.alignment = PP_ALIGN.CENTER
    run = p.runs[0]
    run.font.size = Pt(42)
    run.font.bold = True
    run.font.color.rgb = RGBColor(255, 255, 255)

    subtitle_box = slide.shapes.add_textbox(Inches(2.0), Inches(3.35), Inches(9.3), Inches(0.6))
    subtitle_frame = subtitle_box.text_frame
    subtitle_frame.clear()
    p = subtitle_frame.paragraphs[0]
    p.text = subtitle
    p.alignment = PP_ALIGN.CENTER
    run = p.runs[0]
    run.font.size = Pt(20)
    run.font.color.rgb = RGBColor(220, 230, 240)


def _add_content_slide(prs: Presentation, title: str, body: list[str], bullets: list[str]) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_background(slide, RGBColor(248, 250, 252))

    title_box = slide.shapes.add_textbox(Inches(0.7), Inches(0.45), Inches(12), Inches(0.7))
    title_frame = title_box.text_frame
    title_frame.clear()
    p = title_frame.paragraphs[0]
    p.text = title
    run = p.runs[0]
    run.font.size = Pt(30)
    run.font.bold = True
    run.font.color.rgb = RGBColor(20, 55, 85)

    content_box = slide.shapes.add_textbox(Inches(0.95), Inches(1.55), Inches(11.4), Inches(5.3))
    frame = content_box.text_frame
    frame.word_wrap = True
    frame.clear()

    items = [*body, *bullets]
    if not items:
        items = [" "]

    for idx, item in enumerate(items):
        p = frame.paragraphs[0] if idx == 0 else frame.add_paragraph()
        p.text = item
        p.level = 0
        p.space_after = Pt(8)
        run = p.runs[0]
        run.font.size = Pt(21)
        run.font.color.rgb = RGBColor(30, 41, 59)

    footer = slide.shapes.add_textbox(Inches(0.7), Inches(7.0), Inches(12), Inches(0.3))
    footer_frame = footer.text_frame
    footer_frame.clear()
    p = footer_frame.paragraphs[0]
    p.text = "Generated by PPT Generator"
    p.alignment = PP_ALIGN.RIGHT
    run = p.runs[0]
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(100, 116, 139)


def _add_background(slide, color: RGBColor) -> None:
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color
